/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.personProfile;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author asus
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJPanel
     */
    
    personProfile personprofile;
    
    public CreateJPanel(personProfile personprofile) {
        initComponents();
        
        this.personprofile = personprofile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lbltelephoneNumber = new javax.swing.JLabel();
        lblFAXNumber = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalRecordNum = new javax.swing.JLabel();
        lblHealthPlanBeneficiaryNum = new javax.swing.JLabel();
        lblBankAccountNum = new javax.swing.JLabel();
        lblLiscenceNum = new javax.swing.JLabel();
        lblVechicalIdentifierNum = new javax.swing.JLabel();
        lblDeviceSerialNumber = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        lblUniqueIdentifierNumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFAXNumber = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtSSNNumber = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtHealthPlanBeneficiaryNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtLiscenceNumber = new javax.swing.JTextField();
        txtVechicalIdentifierNumber = new javax.swing.JTextField();
        txtDeviceSerialNumber = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        txtUniqueIdentifierNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfAddress = new javax.swing.JTextArea();
        lblPhotoUpload = new javax.swing.JLabel();
        lblBiometricUpload = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtDOB = new javax.swing.JTextField();
        btnUploadPhoto = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Person Profile");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name: ");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDOB.setText("Date of Birth: ");
        lblDOB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbltelephoneNumber.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbltelephoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbltelephoneNumber.setText("Telephone Number: ");
        lbltelephoneNumber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblFAXNumber.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblFAXNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFAXNumber.setText("FAX Number: ");
        lblFAXNumber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblEmailID.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblEmailID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailID.setText("Email ID: ");
        lblEmailID.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblSSN.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("SSN Number: ");
        lblSSN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblMedicalRecordNum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblMedicalRecordNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedicalRecordNum.setText("Medical Record Number: ");
        lblMedicalRecordNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblHealthPlanBeneficiaryNum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblHealthPlanBeneficiaryNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHealthPlanBeneficiaryNum.setText("Health Plan Beneficiary Number: ");
        lblHealthPlanBeneficiaryNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblBankAccountNum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBankAccountNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBankAccountNum.setText("Bank Account Number: ");
        lblBankAccountNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblLiscenceNum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblLiscenceNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLiscenceNum.setText("Liscence Number:  ");
        lblLiscenceNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVechicalIdentifierNum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblVechicalIdentifierNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblVechicalIdentifierNum.setText("Vechical Identifier Number: ");
        lblVechicalIdentifierNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblDeviceSerialNumber.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDeviceSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeviceSerialNumber.setText("Device Serial Number: ");
        lblDeviceSerialNumber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblLinkedIn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLinkedIn.setText("LinkedIn: ");
        lblLinkedIn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblIPAddress.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblIPAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblIPAddress.setText("IP Address: ");
        lblIPAddress.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblUniqueIdentifierNumber.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblUniqueIdentifierNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUniqueIdentifierNumber.setText("Unique Identifier Number: ");
        lblUniqueIdentifierNumber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });
        txtTelephoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneNumberKeyReleased(evt);
            }
        });

        txtFAXNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXNumberActionPerformed(evt);
            }
        });

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });

        txtSSNNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNNumberActionPerformed(evt);
            }
        });

        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });

        txtHealthPlanBeneficiaryNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthPlanBeneficiaryNumberActionPerformed(evt);
            }
        });

        txtBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumberActionPerformed(evt);
            }
        });

        txtLiscenceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLiscenceNumberActionPerformed(evt);
            }
        });

        txtVechicalIdentifierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVechicalIdentifierNumberActionPerformed(evt);
            }
        });

        txtDeviceSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceSerialNumberActionPerformed(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });

        txtUniqueIdentifierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdentifierNumberActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Address: ");

        txtfAddress.setColumns(20);
        txtfAddress.setRows(5);
        jScrollPane1.setViewportView(txtfAddress);

        lblPhotoUpload.setText("Photo Upload: ");

        lblBiometricUpload.setText("Biometric :");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUploadPhoto.setText("Upload Photo");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUniqueIdentifierNumber)
                            .addComponent(lblIPAddress)
                            .addComponent(lblLinkedIn)
                            .addComponent(lblDeviceSerialNumber)
                            .addComponent(lblVechicalIdentifierNum)
                            .addComponent(lblLiscenceNum)
                            .addComponent(lblBankAccountNum)
                            .addComponent(lblHealthPlanBeneficiaryNum)
                            .addComponent(lblMedicalRecordNum)
                            .addComponent(lblSSN)
                            .addComponent(lblEmailID)
                            .addComponent(lblFAXNumber)
                            .addComponent(lbltelephoneNumber)
                            .addComponent(lblDOB)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLinkedIn)
                            .addComponent(txtDeviceSerialNumber)
                            .addComponent(txtVechicalIdentifierNumber)
                            .addComponent(txtLiscenceNumber)
                            .addComponent(txtBankAccountNumber)
                            .addComponent(txtHealthPlanBeneficiaryNumber)
                            .addComponent(txtMedicalRecordNumber)
                            .addComponent(txtSSNNumber)
                            .addComponent(txtEmailID)
                            .addComponent(txtFAXNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtTelephoneNumber)
                            .addComponent(txtIPAddress)
                            .addComponent(txtUniqueIdentifierNumber)
                            .addComponent(txtName)
                            .addComponent(txtDOB))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(btnUploadPhoto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBiometricUpload))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lblPhotoUpload))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBankAccountNum, lblDOB, lblDeviceSerialNumber, lblEmailID, lblFAXNumber, lblHealthPlanBeneficiaryNum, lblIPAddress, lblLinkedIn, lblLiscenceNum, lblMedicalRecordNum, lblName, lblSSN, lblUniqueIdentifierNumber, lblVechicalIdentifierNum, lbltelephoneNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBankAccountNumber, txtDeviceSerialNumber, txtEmailID, txtFAXNumber, txtHealthPlanBeneficiaryNumber, txtIPAddress, txtLinkedIn, txtLiscenceNumber, txtMedicalRecordNumber, txtName, txtSSNNumber, txtTelephoneNumber, txtUniqueIdentifierNumber, txtVechicalIdentifierNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltelephoneNumber)
                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFAXNumber)
                            .addComponent(txtFAXNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailID)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSSN)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedicalRecordNum)
                            .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealthPlanBeneficiaryNum)
                            .addComponent(txtHealthPlanBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUploadPhoto)
                            .addComponent(lblPhotoUpload)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(txtSSNNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountNum)
                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBiometricUpload))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLiscenceNum)
                    .addComponent(txtLiscenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVechicalIdentifierNum)
                    .addComponent(txtVechicalIdentifierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceSerialNumber)
                    .addComponent(txtDeviceSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddress)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueIdentifierNumber)
                    .addComponent(txtUniqueIdentifierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBankAccountNum, lblDOB, lblDeviceSerialNumber, lblEmailID, lblFAXNumber, lblHealthPlanBeneficiaryNum, lblIPAddress, lblLinkedIn, lblLiscenceNum, lblMedicalRecordNum, lblName, lblSSN, lblUniqueIdentifierNumber, lblVechicalIdentifierNum, lbltelephoneNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBankAccountNumber, txtDeviceSerialNumber, txtEmailID, txtFAXNumber, txtHealthPlanBeneficiaryNumber, txtIPAddress, txtLinkedIn, txtLiscenceNumber, txtMedicalRecordNumber, txtName, txtSSNNumber, txtTelephoneNumber, txtUniqueIdentifierNumber, txtVechicalIdentifierNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtFAXNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXNumberActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void txtSSNNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNNumberActionPerformed

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtHealthPlanBeneficiaryNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberActionPerformed

    private void txtBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumberActionPerformed

    private void txtLiscenceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLiscenceNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLiscenceNumberActionPerformed

    private void txtVechicalIdentifierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVechicalIdentifierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVechicalIdentifierNumberActionPerformed

    private void txtDeviceSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceSerialNumberActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtUniqueIdentifierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdentifierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdentifierNumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        personprofile.setName(txtName.getText());
        
      
        //personprofile.setTelephoneNumber(int.parseInt(txtTelephoneNumber.getText()));
        personprofile.setTelephoneNumber(Long.parseLong(txtTelephoneNumber.getText()));
        
         personprofile.setGeographicData(txtfAddress.getText());
        
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        try {
            //Date d = new Date();
            //personprofile.setDOB(sdf.parse(txtDOB.getText()));
            personprofile.setDOB(sdf.parse(txtDOB.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         personprofile.setFaxNumber(Long.parseLong(txtFAXNumber.getText()));
         personprofile.setEmailID((txtEmailID.getText()));
         personprofile.setSsnNumber(Long.parseLong(txtSSNNumber.getText()));
         personprofile.setMedicalRecordNumber(Long.parseLong(txtMedicalRecordNumber.getText()));
         personprofile.setHealthPlanBeneficiaryNumber(Long.parseLong(txtHealthPlanBeneficiaryNumber.getText()));
         personprofile.setBankAccountNumber(Long.parseLong(txtBankAccountNumber.getText()));
         personprofile.setLiscenceNumber(txtLiscenceNumber.getText());
         personprofile.setVechicalIdentifierNumber(txtVechicalIdentifierNumber.getText());
         personprofile.setDeviceSerialNumber(txtDeviceSerialNumber.getText());
         personprofile.setLinkedIn(txtLinkedIn.getText());
         personprofile.setIpAddress(txtIPAddress.getText());
         personprofile.setUniqueIdentifierNumber(Long.parseLong(txtUniqueIdentifierNumber.getText()));
         // Message box to show the message upon saving Person Profile 
         
         
         
         // Empty Data Validation
         
         //if (personprofile.getName().trim().isEmpty() && personprofile.getDOB().trim().isEmpty()){
         //   JOptionPane.showMessageDialog(this, "all data cannot be blank.");         
          //  txtName.grabFocus(); // blink cursor
           // return;
         //}
         
         
         
         JOptionPane.showMessageDialog(this, "Person Profile Saved Successfully.");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select the File to upload.");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            File file = fileChooser.getSelectedFile();
            BufferedImage bufferedimage;
            BufferedImage img = null;
        
        try {
                 bufferedimage = ImageIO.read(file);
                Image dimg = bufferedimage.getScaledInstance(lblPhoto.getWidth(),lblPhoto.getHeight(),Image.SCALE_SMOOTH);

        ImageIcon icon = new ImageIcon(dimg);
        lblPhoto.setIcon(icon);
        personprofile.setPhoto_Image(icon);

    } catch(IOException e) {

      e.printStackTrace(); // todo: implement proper error handeling

    }
        }


       
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    private void txtTelephoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNumberKeyReleased
        // TODO add your handling code here:
    //VALASHISH
      //  String telePhoneNumber = txtTelephoneNumber.getText();
       // if(telePhoneNumber.matches("^[0-9]*$") && telePhoneNumber.length()== 10)
        //{
         //   txtTelephoneNumber.setBackground(Color.green);
           
       // }
        //else
        //{
        //    txtTelephoneNumber.setBackground(new Color(255,102,102));
             //.showMessageDialog(this, "Invalid Mobile Number.");
        //}
    }//GEN-LAST:event_txtTelephoneNumberKeyReleased

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBankAccountNum;
    private javax.swing.JLabel lblBiometricUpload;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceSerialNumber;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFAXNumber;
    private javax.swing.JLabel lblHealthPlanBeneficiaryNum;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblLiscenceNum;
    private javax.swing.JLabel lblMedicalRecordNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoUpload;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueIdentifierNumber;
    private javax.swing.JLabel lblVechicalIdentifierNum;
    private javax.swing.JLabel lbltelephoneNumber;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceSerialNumber;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFAXNumber;
    private javax.swing.JTextField txtHealthPlanBeneficiaryNumber;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtLiscenceNumber;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSNNumber;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtUniqueIdentifierNumber;
    private javax.swing.JTextField txtVechicalIdentifierNumber;
    private javax.swing.JTextArea txtfAddress;
    // End of variables declaration//GEN-END:variables
}
